<div class="alert alert-info">
    <h1 align="center">Normal Equation</h1>
    <h3 align="center"> Machine Learning (Fall 2018)</h3>
    <h5 align="center">Seyed Naser Razavi [ML2018](http://www.snrazavi.ir/ml-2018/)</h5>
</div>

## Introduction

<img src='imgs/normal_equation_detail.png' width='75%'>

**Goal.** Given $X$ and $y$, our goal is to find $\theta$ such that: 

$$X \theta = y$$

1. To solve the above equation for $\theta$, first we multiply both sides by $X^T$

$$X^T X\theta = X^T y$$ 

2. Now, we can compute the **inverse** matrix of $X^T X$ and multiply it on both sides of the above equation.

$$(X^T X)^{-1} (X^T X) \theta = (X^T X)^{-1} X^T y$$ 

Hence, we obtatin

$$\theta = (X^T X)^{-1} X^T y = X^{+} y$$ 

<div class="alert alert-info">
    <strong>Pseudo-inverse:</strong> In the above equation, $X^+$ is called pseudo-inverse.
</div>

## Implentation in Python

In [1]:
import numpy as np
from numpy.linalg import pinv  # pseudo-inverse

np.set_printoptions(precision=2, sign=' ', suppress=True)

### Inputs (design matrix)

In [2]:
X = np.array([[1, 2104, 5, 1, 45],
              [1, 1416, 3, 2, 40],
              [1, 1534, 3, 2, 30],
              [1,  852, 2, 1, 36]])

In [3]:
print(X)

[[   1 2104    5    1   45]
 [   1 1416    3    2   40]
 [   1 1534    3    2   30]
 [   1  852    2    1   36]]


### Outputs (targets)

In [4]:
y = np.array([[460.],
              [232.],
              [315.],
              [178.]])

In [5]:
print(y)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


### Solving Normal Equation

$$\theta = (X^T X)^{-1} X^T y = X^{+} y$$

In [ ]:
# ??np.linalg.pinv  # getting help

In [6]:
theta = pinv(X) @ y

In [7]:
theta

array([[188.4 ],
       [  0.39],
       [-56.14],
       [-92.97],
       [ -3.74]])

In [8]:
print(X @ theta)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [9]:
print(y)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [10]:
print(X @ theta == y)      # Wrong way to campare to float matrices

[[False]
 [False]
 [False]
 [False]]


In [11]:
np.allclose(X @ theta, y)  # correct way for comparing numpy matrices

True

### Better option:

The matrix $X^T X$ may not be invertible.

In [12]:
theta = pinv(X.T @ X) @ X.T @ y

In [13]:
theta

array([[188.4 ],
       [  0.39],
       [-56.14],
       [-92.97],
       [ -3.74]])

In [14]:
np.allclose(X @ theta, y)

True

## Inverse and Pseudo-Inverse

<div class="alert alert-info">
    <strong>Inverse: ($A^{-1}$)</strong>
    $$A A^{-1} = A^{-1} A = I$$
</div>

<div class="alert alert-info">
    <strong>Pseudo-inverse: ($A^{+}$)</strong>
    $$A^{+} = (A^T A)^{-1} A^T$$
</div>

In [18]:
from numpy.linalg import inv, pinv

In [19]:
A = np.random.randn(3, 3)

In [20]:
A

array([[ 0.38, -1.31,  0.86],
       [-1.1 , -0.88, -0.7 ],
       [-0.5 ,  0.11, -0.67]])

In [21]:
inv(A)

array([[ 2.39, -2.8 ,  5.95],
       [-1.38,  0.62, -2.41],
       [-2.02,  2.19, -6.33]])

In [22]:
pinv(A)

array([[ 2.39, -2.8 ,  5.95],
       [-1.38,  0.62, -2.41],
       [-2.02,  2.19, -6.33]])

Check for equality

In [23]:
np.allclose(inv(A), pinv(A))

True

<div class="alert alert-success">
    <strong>Question:</strong> So, what is the difference between `inv` and `pinv`
</div>

<div class="alert alert-info">
    <strong>Theorem:</strong> If matrix $A$ is **non-singular**, then $A^{-1} = A^{+}$.
</div>

**Proof.**

$$A^{+} = (A^T A)^{-1} A^T = (A^{-1} (A^T)^{-1}) A^T = A^{-1} ((A^T)^{-1} A^T) = A^{-1} I = A^{-1}$$

But, what if the matrix is **singular**?

In [24]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [2, 4, 6]])

Now, if we try to compute `inv(A)`, we will get a `LinAlgError`! (try it yourself)

<img src='imgs/linAlgError-SingularMatrix.png' width='76%'>

In [26]:
pinv(A)

array([[-0.19,  0.44, -0.38],
       [-0.02,  0.11, -0.04],
       [ 0.14, -0.22,  0.29]])

## Another Example

In [ ]:
# inputs (or design matrix)
X = np.array([[1, 2104, 5, 1, 45],
              [1, 1416, 3, 2, 40],
              [1, 1534, 3, 2, 30],
              [1,  852, 2, 1, 36], 
              [1, 3000, 4, 1, 38]])

In [ ]:
# desired outputs
y = np.array([[460.],
              [232.],
              [315.],
              [178.], 
              [540.]])

In [ ]:
theta = pinv(X.T @ X) @ X.T @ y

In [ ]:
theta

In [ ]:
X @ theta

In [ ]:
y

In [ ]:
np.allclose(X @ theta, y)

## Psuedo-inverse properties (optional)

<div class="alert alert-info">
    <strong>Property 1:</strong>
    $$(A^+)^+ = A$$
</div>

In [27]:
np.allclose(pinv(pinv(X)), X)

True

<div class="alert alert-info">
    <strong>Property 2:</strong>
    $$A A^+ A = A$$
</div>

In [28]:
np.allclose(X @ pinv(X) @ X, X)

True

<div class="alert alert-info">
    <strong>Property 3:</strong>
    $$A^+ A A^+ = A^+$$
</div>

In [29]:
np.allclose(pinv(X) @ X @ pinv(X), pinv(X))

True